version: '3.8'
services:
  nginxwebsvr:
    image: nginx:latest
    container_name: nginxwebsvr
    ports:
      - "80:80"   
  mysqldb:
    image: mysql:5.7
    restart: always
    volumes:
    - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: flaskdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass  
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - db
    ports:
      - "9000:9000"
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   container_name: jenkins
  #   ports:
  #     - "8081:8080"
  #     - "50000:50000"
  #   environment:
  #     - DOCKER_HOST=tcp://host.docker.internal:2375
  #   volumes:
  #     - jenkins_home:/var/jenkins_home
  app:
    build: .
    container_name: flask_app_lab10
    ports:
      - "5000:5000"
    # depends_on:
    #   - jenkins
  

# volumes:
#   jenkins_home:
