version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375
    volumes:
      - jenkins_home:/var/jenkins_home
  app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - jenkins
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  jenkins_home:
